# Generated by Django 3.0.2 on 2020-02-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phoneno', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dematAccntNo', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('purchaseCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaseDate', models.DateTimeField(verbose_name='Date of stock purchase')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaryanalysis.User')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rateOfInt', models.IntegerField()),
                ('bankName', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaryanalysis.User')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaryanalysis.User')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rateOfInt', models.IntegerField()),
                ('bankName', models.CharField(max_length=100)),
                ('dueDate', models.DateTimeField(verbose_name='last date for clearence')),
                ('statusofclearence', models.BooleanField(default=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaryanalysis.User')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('transactionDate', models.DateTimeField(verbose_name='date of transaction')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaryanalysis.User')),
            ],
        ),
    ]
