# Generated by Django 3.0.2 on 2020-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetaryanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='accountNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='accountNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savings',
            name='accountNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
